### ISSUE TITLE
请问这个怎么集成到data2 文件中呢

### ISSUE THREAD

**Issue by p578559783** [RobinCodeX/solid-panorama#1]
请问下这个怎么和data2 关联起来呢？

**Comment by robincodex** [comment]
参考项目 https://github.com/robincodex/solid-panorama-example.git

**Comment by p578559783** [comment]
请问你一下，一般去哪个地方学习这个dota2 rpg的开发呢，刚接触，好多懵逼的，谢谢

**Comment by robincodex** [comment]
QQ群：347735258
